spring:
  application:
    name: ${APP_NAME}
    app-version: ${API_VERSION}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:mercadoSpring}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:antipas120}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    open-in-view: false

server:
  port: ${APPLICATION_PORT}

# JWT Configuration
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
  refresh-access-token: ${REFRESH_ACCESS_TOKEN}

# Stripe Configuration
stripe:
  apiKey: ${STRIPE_API_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}

# Firebase Configuration
firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  client-id: ${FIREBASE_CLIENT_ID}
  auth-url: ${FIREBASE_AUTH_URL}
  token-url: ${FIREBASE_TOKEN_URL}
  cert-url: ${FIREBASE_CERT_URL}

logging:
  level:
    org.springframework.mail: INFO
    org:
      springframework:
        security: DEBUG
    jakarta.mail: WARN



